spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  structured:
    format:
      file: ecs
  file:
    name: log.json
